// Bug happens on JVM -Xuse-ir
//File: tmp/tmp0.kt

fun test() {
try
{{ a, 
 -> 
 }}
catch(foo: Exception){}
}
