// Bug happens on JVM , JS 
// FILE: tmp0.kt


fun zap() = "OK"
fun test() = "OK"
fun String(x: Double) = "OK"
fun JvmDefault() = "K"
fun zap(s: String) = s

inline fun Sequence(C: String, ia: String, rType: String) =
        "OK"
inline fun gs(index: Int) =
        "OK"
private inline fun tryZap(a: String, s2: String, fn: String.(String) -> String) =
        fn(
                try{
println("""TRY""");
 

val c = (false)
if (c) {
println("""THEN""");
zap()
} else {
println("""ELSE""");
zap("O")
}
} catch (e: Exception){
println("""CATCH e: Exception""");

        "Exception: ${e.message}"
},
                try {
println("""TRY""");
zap()
} catch (String: Exception){
println("""CATCH String: Exception""");
 
(s2)

val q = true
{ "OK" }

{ zap() }
s2

String
{ zap() }
if (q) {
println("""THEN""");
throw AssertionError()
} else {
println("""ELSE""");
"Fail no message"
}
}
        )

fun box(): String = tryZap("java.util.Iterator", "zzz") { 
val y = true

when (y) {
 false -> {
println("""WHEN false""");
this + it
}
 else -> {
println("""WHEN """);
this + String
}
}
 }
